import { expect, test, type Page } from '@playwright/test';
import { answerWorldPoint } from './map-interaction';

// Keep frozen review dates independent of Leaflet's wall-clock animations.
test.use({ reducedMotion: 'reduce' });

async function openFacetSetup(page: Page) {
  await page.getByRole('button', { name: 'Custom practice', exact: true }).click();
  const setup = page.getByRole('dialog', { name: 'Custom practice setup' });
  await setup.getByRole('radio', { name: 'Countries & territories', exact: true }).check();
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  return setup;
}

test('a guest chooses country practice through the guided facet setup', async ({ page }) => {
  await page.goto('/');
  const setup = await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Name-to-location', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(setup).toBeHidden();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  const selection = page.getByRole('region', { name: 'Current practice selection' });
  await expect(selection).toContainText('Countries & territories');
  await expect(selection).toContainText('Worldwide');
  await expect(selection).toContainText('Name-to-location');
});

test('recognition hides the target name and grades an exact selected country instead of typed text', async ({ page }) => {
  await page.goto('/');
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('South America');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Location-to-name recognition', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeHidden();
  await expect(page.getByRole('region', { name: 'Country fact card' })).toBeHidden();
  await expect(page.getByRole('region', { name: 'World map', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Country close-up' })).toBeHidden();
  await expect(page.getByRole('region', { name: 'World map', exact: true })).not.toContainText('Brazil');
  const search = page.getByRole('combobox', { name: 'Search countries & territories' });
  const check = page.getByRole('button', { name: 'Check country' });
  await search.fill('Brazil');
  await expect(check).toBeDisabled();
  await search.fill('Argentina');
  await search.press('ArrowDown');
  await search.press('Enter');
  await check.click();
  await expect(page.getByRole('status')).toContainText('Not quite');
  await expect(page.getByRole('status')).toContainText('Argentina');
  await expect(page.getByRole('region', { name: 'Country fact card' })).toContainText('Brazil');
  await page.getByRole('button', { name: 'Retry now' }).click();
  await search.fill('Brazil');
  await page.getByRole('option', { name: 'Brazil', exact: true }).click();
  await check.click();
  await expect(page.getByRole('status')).toContainText('Correct');
  await page.reload();
  await expect(page.getByRole('status')).toContainText('Correct');
  await expect(page.getByRole('region', { name: 'Country fact card' })).toContainText('Brazil');
});

test('recognition keeps the selected globe through answers and makes close-up exploration optional', async ({ page }) => {
  await page.goto('/');
  await page.getByRole('button', { name: 'Switch to 3D globe', exact: true }).click();
  const setup = await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Location-to-name recognition', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  const globe = page.getByRole('application', { name: 'Interactive globe' });
  const closeUp = page.getByRole('region', { name: 'Country close-up' });
  await expect(globe).toBeVisible();
  await expect(closeUp).toBeHidden();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeHidden();
  const search = page.getByRole('combobox', { name: 'Search countries & territories' });
  await search.fill('Argentina');
  await page.getByRole('option', { name: 'Argentina', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await page.getByRole('button', { name: 'Retry now' }).click();
  await expect(globe).toBeVisible();
  await expect(closeUp).toBeHidden();
  await search.fill('Brazil');
  await page.getByRole('option', { name: 'Brazil', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(globe).toBeVisible();
  await expect(closeUp).toBeHidden();
  await page.getByRole('button', { name: 'Switch to 2D map', exact: true }).click();
  const world = page.getByRole('region', { name: 'World map', exact: true });
  await expect(world).toBeVisible();
  await page.getByRole('button', { name: 'Explore target', exact: true }).click();
  await expect(closeUp).toBeVisible();
  await expect(closeUp).not.toContainText('China');
  await expect(page.getByRole('region', { name: 'Regional overview' })).not.toContainText('China');
  await page.getByRole('button', { name: 'Back to world map', exact: true }).click();
  await expect(world).toBeVisible();
  await search.fill('China');
  await page.getByRole('option', { name: "People's Republic of China", exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await expect(page.getByRole('status')).toContainText('Correct — country identified.');
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(world).toBeVisible();
  await expect(closeUp).toBeHidden();
  await page.reload();
  await expect(world).toBeVisible();
  await expect(closeUp).toBeHidden();
});

test('recognition search normalizes names and aliases without leaving the selected region', async ({ page }) => {
  await page.goto('/');
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Europe');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Northern Europe');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Location-to-name recognition', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  const search = page.getByRole('combobox', { name: 'Search countries & territories' });
  await search.fill('a.LÁN-D');
  await expect(page.getByRole('option')).toHaveText(['Åland']);
  await search.fill('u.k.');
  await expect(page.getByRole('option')).toHaveText(['United Kingdom']);
  await page.getByRole('option', { name: 'United Kingdom', exact: true }).click();
  const check = page.getByRole('button', { name: 'Check country' });
  await expect(check).toBeEnabled();
  await search.fill('Russia');
  await expect(check).toBeDisabled();
  await expect(page.getByRole('option')).toHaveCount(0);
  await search.fill('United States');
  await expect(page.getByRole('option')).toHaveCount(0);
  await search.fill('Åland');
  await search.press('Enter');
  await expect(check).toBeDisabled();
  await search.press('ArrowDown');
  await search.press('Enter');
  await check.click();
  await expect(page.getByRole('status')).toContainText('You selected Åland');
});

test('recognition retries and scheduled reviews keep proficiency independent of spatial recall', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-07T12:00:00Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start country session' }).click();
  await answerWorldPoint(page, -52, -12);
  const recall = page.getByRole('region', { name: 'Name-to-location proficiency' });
  const recallDue = await recall.locator('time').getAttribute('datetime');
  const setup = await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Location-to-name recognition', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  const recognition = page.getByRole('region', { name: 'Location-to-name recognition proficiency' });
  await expect(recognition).toBeHidden();
  await expect(page.getByText('New learning item', { exact: true })).toBeVisible();
  const search = page.getByRole('combobox', { name: 'Search countries & territories' });
  await search.fill('Argentina');
  await page.getByRole('option', { name: 'Argentina', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await expect(recognition).toContainText('Learning');
  await expect(recognition.locator('time')).toHaveAttribute('datetime', '2026-09-07T12:10:00.000Z');
  await page.getByRole('button', { name: 'Retry now' }).click();
  await search.fill('Brazil');
  await page.getByRole('option', { name: 'Brazil', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await expect(recognition).toContainText('Learning');
  await expect(recognition.locator('time')).toHaveAttribute('datetime', '2026-09-07T12:10:00.000Z');
  await page.clock.setFixedTime(new Date('2026-09-07T12:10:00Z'));
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(page.getByText('Scheduled review', { exact: true })).toBeVisible();
  await search.fill('Brazil');
  await page.getByRole('option', { name: 'Brazil', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  await expect(recognition).toContainText('Familiar');
  const recognitionDue = await recognition.locator('time').getAttribute('datetime');
  const reviewTime = Math.max(Date.parse(recallDue!), Date.parse(recognitionDue!));
  await page.clock.setFixedTime(new Date(reviewTime));
  await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Name-to-location', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(recall).toContainText('Familiar');
  await expect(recall.locator('time')).toHaveAttribute('datetime', recallDue!);
  await answerWorldPoint(page, -52, -12);
  await expect(recall).toContainText('Retained');
  const nextRecallDue = await recall.locator('time').getAttribute('datetime');
  expect(Date.parse(nextRecallDue!)).toBeGreaterThan(reviewTime);
  await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Location-to-name recognition', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(recognition).toContainText('Familiar');
  await expect(recognition.locator('time')).toHaveAttribute('datetime', recognitionDue!);
  await search.fill('Brazil');
  await page.getByRole('option', { name: 'Brazil', exact: true }).click();
  await page.getByRole('button', { name: 'Check country' }).click();
  const nextRecognitionDue = await recognition.locator('time').getAttribute('datetime');
  expect(Date.parse(nextRecognitionDue!)).toBeGreaterThan(reviewTime);
  await page.reload();
  await expect(recognition).toContainText('Retained');
  await expect(recognition.locator('time')).toHaveAttribute('datetime', nextRecognitionDue!);
  await page.clock.setFixedTime(new Date(Math.max(Date.parse(nextRecallDue!), reviewTime)));
  await openFacetSetup(page);
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Name-to-location', exact: true }).check();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(recall.locator('time')).toHaveAttribute('datetime', nextRecallDue!);
});


test('regional country practice stays filtered across questions and reloads', async ({ page }) => {
  await page.goto('/');
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Asia');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Eastern Asia');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await answerWorldPoint(page, 105, 35);
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(page.getByRole('heading', { name: /Japan/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: /Japan/ })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Current practice selection' })).toContainText('Eastern Asia');
  await page.getByRole('button', { name: 'Edit practice set' }).click();
  await setup.getByRole('button', { name: '2 Geography' }).click();
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Europe');
  await expect(setup.getByRole('combobox', { name: 'Region', exact: true })).toHaveValue('All regions');
  await setup.getByRole('button', { name: 'Cancel', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Japan/ })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Current practice selection' })).toContainText('Eastern Asia');
});

test('adaptive and facet practice share proficiency without dropping out-of-scope reviews', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-07T12:00:00Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start country session' }).click();
  await answerWorldPoint(page, -52, -12);
  const proficiency = page.getByRole('region', { name: 'Name-to-location proficiency' });
  await expect(proficiency).toContainText('Familiar');
  const firstDue = await proficiency.locator('time').getAttribute('datetime');
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Asia');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Eastern Asia');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await answerWorldPoint(page, 105, 35);
  await page.clock.setFixedTime(new Date(firstDue!));
  await page.getByRole('button', { name: 'Recommended practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await expect(page.getByText('Scheduled review', { exact: true })).toBeVisible();
  await answerWorldPoint(page, -52, -12);
  await expect(proficiency).toContainText('Retained');
  const secondDue = await proficiency.locator('time').getAttribute('datetime');
  expect(Date.parse(secondDue!)).toBeGreaterThan(Date.parse(firstDue!));
  await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('South America');
  await page.clock.setFixedTime(new Date(secondDue!));
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await expect(page.getByText('Scheduled review', { exact: true })).toBeVisible();
  await answerWorldPoint(page, -52, -12);
  const thirdDue = await proficiency.locator('time').getAttribute('datetime');
  expect(Date.parse(thirdDue!)).toBeGreaterThan(Date.parse(secondDue!));
  await page.reload();
  await expect(proficiency).toContainText('Retained');
  await expect(proficiency.locator('time')).toHaveAttribute('datetime', thirdDue!);
  await page.getByRole('button', { name: 'Recommended practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await expect(page.getByText('Scheduled review', { exact: true })).toBeVisible();
  await expect(page.getByLabel('Practice results')).toContainText('4 answered');
});

test('filtered fact reading resumes without assessing countries or rescheduling reviews', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-07T12:00:00Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start country session' }).click();
  await answerWorldPoint(page, -52, -12);
  const proficiency = page.getByRole('region', { name: 'Name-to-location proficiency' });
  const dueAt = await proficiency.locator('time').getAttribute('datetime');
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Asia');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Eastern Asia');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Country fact cards', exact: true }).check();
  await setup.getByRole('button', { name: 'Start reading', exact: true }).click();
  const card = page.getByRole('region', { name: 'Country fact card' });
  await expect(card.getByRole('heading', { name: /China/ })).toBeVisible();
  await expect(card).toContainText('Informational · not scored');
  await expect(page.getByRole('button', { name: 'Check location' })).toBeHidden();
  await page.getByRole('button', { name: 'Next fact card' }).click();
  await expect(card.getByRole('heading', { name: 'Japan', exact: true })).toBeVisible();
  await page.reload();
  await expect(card.getByRole('heading', { name: 'Japan', exact: true })).toBeVisible();
  await expect(page.getByRole('region', { name: 'Current practice selection' })).toContainText('Country fact cards');
  await expect(page.getByLabel('Practice results')).toContainText('1 answered');
  await page.clock.setFixedTime(new Date(dueAt!));
  await page.getByRole('button', { name: 'Recommended practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await expect(page.getByText('Scheduled review', { exact: true })).toBeVisible();
  await expect(proficiency).toContainText('Familiar');
  await expect(proficiency.locator('time')).toHaveAttribute('datetime', dueAt!);
  await answerWorldPoint(page, -52, -12);
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await expect(page.getByText('New learning item', { exact: true })).toBeVisible();
});

test('switching sets preserves an unanswered guided question across reloads', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-07T12:00:00Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start country session' }).click();
  await page.getByRole('button', { name: 'Show location', exact: true }).click();
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Asia');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Eastern Asia');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await page.reload();
  await page.getByRole('button', { name: 'Recommended practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await expect(page.getByText(/Location help used · guided practice/)).toBeVisible();
  await page.getByRole('button', { name: 'Back to world map', exact: true }).click();
  await answerWorldPoint(page, -52, -12);
  await expect(page.getByRole('status')).toContainText('guided practice');
  const proficiency = page.getByRole('region', { name: 'Name-to-location proficiency' });
  await expect(proficiency).toContainText('Learning');
  await expect(proficiency.locator('time')).toHaveAttribute('datetime', '2026-09-07T12:10:00.000Z');
  await expect(page.getByLabel('Practice results')).toContainText('0 correct');
});

test('fact-map reveals mark current and paused questions as guided without scoring reading', async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-09-07T12:00:00Z'));
  await page.goto('/');
  await page.getByRole('button', { name: 'Start country session' }).click();
  const setup = await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Asia');
  await setup.getByRole('combobox', { name: 'Region', exact: true }).selectOption('Eastern Asia');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('button', { name: 'Start practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await openFacetSetup(page);
  await setup.getByRole('combobox', { name: 'Continent', exact: true }).selectOption('Worldwide');
  await setup.getByRole('button', { name: 'Continue', exact: true }).click();
  await setup.getByRole('radio', { name: 'Country fact cards', exact: true }).check();
  await setup.getByRole('button', { name: 'Start reading', exact: true }).click();
  const card = page.getByRole('region', { name: 'Country fact card' });
  await expect(card.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await page.getByRole('button', { name: 'Next fact card' }).click();
  await expect(card.getByRole('heading', { name: /China/ })).toBeVisible();
  await page.reload();
  await expect(page.getByLabel('Practice results')).toContainText('0 answered');
  await page.getByRole('button', { name: 'Recommended practice', exact: true }).click();
  await expect(page.getByRole('heading', { name: /Brazil/ })).toBeVisible();
  await expect(page.getByText(/Location help used · guided practice/)).toBeVisible();
  await page.getByRole('button', { name: 'Back to world map', exact: true }).click();
  await answerWorldPoint(page, -52, -12);
  const proficiency = page.getByRole('region', { name: 'Name-to-location proficiency' });
  await expect(proficiency).toContainText('Learning');
  await expect(proficiency.locator('time')).toHaveAttribute('datetime', '2026-09-07T12:10:00.000Z');
  await page.getByRole('button', { name: 'Next learning item' }).click();
  await expect(page.getByRole('heading', { name: /China/ })).toBeVisible();
  await expect(page.getByText(/Location help used · guided practice/)).toBeVisible();
});
